name: "HA Keepalived Failover"
version: "1.1.2"
slug: "keepalived-failover"
description: "Failover automatico Home Assistant sul Raspberry di backup"
url: "https://github.com/mirkoa82/ha-keepalived-failover"

arch:
  - aarch64
  - armv7
  - amd64

init: false
startup: services
boot: auto

hassio_api: true
hassio_role: manager
host_network: true

privileged:
  - NET_ADMIN
  - NET_RAW

options:
  master_node_ip: "10.14.0.237"
  virtual_ip: "10.14.0.246"
  prefix_length: 24
  interface: "end0"

  check_interval: 5
  ping_timeout: 2
  tcp_timeout: 3

  failover_failures: 6
  failover_grace_period: 30

  failback_successes: 24
  failback_grace_period: 30

  core_start_timeout: 180
  core_stop_timeout: 60

  post_vip_add_delay: 3
  post_vip_remove_delay: 3

  # true: prova add/rimozione VIP e termina, senza toccare il Core.
  test_vip_only: false
  vip_test_duration: 10

schema:
  master_node_ip: str
  virtual_ip: str
  prefix_length: int(1,32)
  interface: str

  check_interval: int(1,60)
  ping_timeout: int(1,15)
  tcp_timeout: int(1,30)

  failover_failures: int(1,120)
  failover_grace_period: int(0,900)

  failback_successes: int(1,360)
  failback_grace_period: int(0,1800)

  core_start_timeout: int(15,900)
  core_stop_timeout: int(15,600)

  post_vip_add_delay: int(0,60)
  post_vip_remove_delay: int(0,60)

  test_vip_only: bool
  vip_test_duration: int(1,120)
